import { LoginForm } from "@/components/LoginForm";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Bienes Raices | Iniciar Sesion",
  description: "Generated by create next app",
};

export default function LoginPage() {
  return (
    <div className="py-10">
      <h1 className="text-4xl font-extrabold text-center">
        Bienes
        <span className="font-normal">Raices</span>
      </h1>
      <h2 className="text-center text-2xl font-extrabold">
        Iniciar Sesion
      </h2>
      <div className="mt-8 mx-auto max-w-md">
        <LoginForm />
      </div>
    </div>
  )
}