'use client'

import { Metadata } from "next";
import { InputsRegister, RegisterForm } from "@/components/RegisterForm";
import userService from '../../../services/user';
import { useState } from "react";
import endpoints from '../../../services'
import Link from "next/link";

export const metadata: Metadata = {
  title: "Bienes Raices | Registro",
  description: "Generated by create next app",
};

export default function RegisterPage() {
  const [showEmailConfirmationMessage, setShowEmailConfirmationMessage] = useState(false)

  const onSubmit = (data: InputsRegister) => {
    userService.registerUser(endpoints.auth.register, data)
      .then(res => {
        if(res) {
          setShowEmailConfirmationMessage(true)
        }
      }).catch(err => console.log(err))
  }

  return (
    <div>
      {
        !showEmailConfirmationMessage && (
          <>
            <h2 className="text-center text-2xl font-extrabold">Crear cuenta</h2>
            <div className="mt-8 mx-auto max-w-md flex flex-col gap-2">
              <RegisterForm onSubmit={onSubmit} />
              <div className="flex items-center justify-between">
                <Link className="flex text-xs text-gray-500" href="/auth/login">
                  ¿Ya tienes una cuenta? Inicia sesión
                </Link>

                <Link className="text-xs text-gray-500"  href="/auth/forgotpassword">
                  ¿Olvidé mi contraseña?
                </Link>
              </div>
            </div>
          </>
        )
      }
      {showEmailConfirmationMessage && (
        <div className="py-10">
          <h1 className="text-4xl font-extrabold text-center">
            Bienes
            <span className="font-normal">Raices</span>
          </h1>
          <p className="text-2xl text-center font-bold">Cuenta creada con correctamente</p>
          <p className="text-lg text-center">Hemos enviado un email para que puedas confirmar tu cuenta</p>
        </div>
      )}
    </div>
  )
}
