import { RegisterForm } from "@/components/RegisterForm";
import { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Bienes Raices | Registro",
  description: "Generated by create next app",
};

export default function RegisterPage() {
  return (
    <div>
      <h2 className="text-center text-2xl font-extrabold">Crear cuenta</h2>
      <div className="mt-8 mx-auto max-w-md">
        <RegisterForm />
        <div className="flex space-y-2 items-center justify-between">
          <Link className="text-xs text-gray-500" href="/auth/login">
            ¿Ya tienes una cuenta? Inicia sesión
          </Link>

          <Link className="text-xs text-gray-500"  href="/auth/forgotpassword">
            ¿Olvidé mi contraseña?
          </Link>
        </div>
      </div>
    </div>
  )
}