import { ForgotPasswordForm } from "@/components/ForgotPasswordForm";
import { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Bienes Raices | Recuperar contraseña",
  description: "Generated by create next app",
};

export default function ForgotPasswordPage() {
  return (
    <div>
    <h2 className="text-center text-2xl font-extrabold">Recuperar contraseña</h2>
    <div className="mt-8 mx-auto max-w-md">
      <ForgotPasswordForm />
      <div className="flex space-y-2 items-center justify-between">
          <Link className="text-xs text-gray-500" href="/auth/register">
            ¿No tienes una cuenta? Regístrate
          </Link>

          <Link className="text-xs text-gray-500"  href="/auth/login">
            Iniciar sesión
          </Link>
        </div>
    </div>
  </div>
  )
}