import { Metadata } from "next"

export const metadata: Metadata = {
  title: "Bienes Raices | Confirmar Cuenta",
  description: "Generated by create next app",
};

export default function ConfirmAccountPage() {
  return (
    <div className="py-10">
      <h1 className="text-4xl font-extrabold text-center">
        Bienes
        <span className="font-normal">Raices</span>
      </h1>
      <p className="text-2xl text-center font-bold">Cuenta creada con correctamente</p>
      <p className="text-lg text-center">Hemos enviado un email para que puedas confirmar tu cuenta</p>
    </div>
  ) 
}